import React, { useState } from 'react';
import { View, Text, TextInput, Button } from 'react-native';
import { getDatabase, ref, push, set } from "firebase/database";
import { db } from "../utils/firebaseHelper";

function CreateGroupScreen({ navigation }) {
  const [groupName, setGroupName] = useState('');

  const handleCreateGroup = () => {
    if (groupName.trim() !== '') {
      // Create a reference to the 'groups' node in the database
      const groupsRef = ref(db, 'groups');
      
      // Push a new group to the database
      const newGroupRef = push(groupsRef);
      
      // Get the unique key generated by push()
      const groupId = newGroupRef.key;
      
      // Define the data for the new group
      const newGroupData = {
        name: groupName.trim(),
        members: {} // Initialize an empty members object
      };
      
      // Set the data for the new group
      set(newGroupRef, newGroupData)
        .then(() => {
          // Group created successfully
          console.log('Group created with ID:', groupId);
          
          // Navigate back to the GroupListScreen and pass the new group ID
          navigation.navigate('Groups', { newGroupId: groupId });
        })
        .catch((error) => {
          console.error('Error creating group:', error);
        });
    }
  };

  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Create a New Group</Text>
      <TextInput
        placeholder="Group Name"
        value={groupName}
        onChangeText={setGroupName}
        style={{ borderWidth: 1, borderColor: 'gray', marginVertical: 10, padding: 8, width: 200 }}
      />
      <Button title="Create Group" onPress={handleCreateGroup} />
    </View>
  );
}

export default CreateGroupScreen;
